//! Security response headers.
//!
//! Adds the headers configured in `[security_headers]` to every response.
//! Values are plain strings for configurability; an **empty value omits
//! the header**. Defaults are a strict, API-appropriate set:
//!
//! | Header                      | Default value                                        |
//! |-----------------------------|------------------------------------------------------|
//! | `X-Content-Type-Options`    | `nosniff`                                            |
//! | `X-Frame-Options`           | `DENY`                                               |
//! | `Referrer-Policy`           | `no-referrer`                                        |
//! | `Content-Security-Policy`   | `default-src 'none'; frame-ancestors 'none'`         |
//! | `Strict-Transport-Security` | `max-age=31536000; includeSubDomains`                |
//!
//! The header pairs are precomputed once at startup from the validated
//! configuration (see [`crate::state::AppState::security_headers`]), so
//! applying them per response only clones small values.
//!
//! This layer is applied outermost (see [`crate::middleware`]) so the
//! headers are present even on responses generated by inner layers
//! (rate limiting, timeouts, body limits) or by the 404 fallback.

use axum::extract::{Request, State};
use axum::middleware::Next;
use axum::response::Response;

use crate::state::AppState;

/// Middleware entry point (see [`crate::middleware`] for ordering).
pub async fn run(State(state): State<AppState>, request: Request, next: Next) -> Response {
    let mut response = next.run(request).await;

    let headers = response.headers_mut();
    for (name, value) in state.security_headers() {
        headers.insert(name, value.clone());
    }

    response
}
