//! Security response headers.
//!
//! Adds the headers configured in `[security_headers]` to every response.
//! Values are plain strings for configurability; an **empty value omits
//! the header**. Defaults are a strict, API-appropriate set:
//!
//! | Header                      | Default value                                        |
//! |-----------------------------|------------------------------------------------------|
//! | `X-Content-Type-Options`    | `nosniff`                                            |
//! | `X-Frame-Options`           | `DENY`                                               |
//! | `Referrer-Policy`           | `no-referrer`                                       |
//! | `Content-Security-Policy`   | `default-src 'none'; frame-ancestors 'none'`        |
//! | `Strict-Transport-Security` | `max-age=31536000; includeSubDomains`                |
//!
//! The header pairs are precomputed once at startup from the validated
//! configuration (see [`crate::state::AppState::security_headers`]), so
//! applying them per response only clones small values.
//!
//! One value is live instead: while the round-trip family is non-empty
//! (a `[auth] cookie_domain`, host names in the vhost table — F19's
//! sign-in round trip), the `Content-Security-Policy`'s
//! `form-action 'self'` is widened with the family's origins, so the
//! browser lets the login form's `303` cross the `Host` line back to
//! the page the visitor came from. The additions mirror the `redirect`
//! allowlist ([`crate::routes::auth`]) by construction; a policy
//! without `form-action 'self'` is left exactly as written (see
//! [`expand_form_action`]).
//!
//! This layer is applied outermost (see [`crate::middleware`]) so the
//! headers are present even on responses generated by inner layers
//! (rate limiting, timeouts, body limits) or by the 404 fallback.

use axum::extract::{Request, State};
use axum::http::header;
use axum::middleware::Next;
use axum::response::Response;

use crate::state::AppState;

/// Middleware entry point (see [`crate::middleware`] for ordering).
pub async fn run(State(state): State<AppState>, request: Request, next: Next) -> Response {
    let mut response = next.run(request).await;

    let headers = response.headers_mut();
    for (name, value) in state.security_headers() {
        headers.insert(name, value.clone());
    }

    // The round-trip family's `form-action` (F19): the live value,
    // swapped after the precomputed pairs so the widened policy (when
    // there is one) wins the single Content-Security-Policy header.
    if let Some(policy) = state.form_action_csp() {
        headers.insert(header::CONTENT_SECURITY_POLICY, policy);
    }

    response
}

/// Appends `family` to the policy's `form-action` directive, but only
/// while that directive says `'self'` — the shape the shipped
/// `wallermax.toml` and every phase before F19 used.
///
/// A form's `303` may only cross the `Host` line when the browser's
/// CSP lets the redirect target through, and `form-action 'self'`
/// pins forms to one origin — the silent wall the first round trip
/// hit (the sign-in POST succeeds, the cookie is stored, and the
/// navigation is swallowed without a single follow-up request). The
/// additions are the same origins the `redirect` allowlist trusts,
/// so the policy admits exactly the family the server sends forms
/// back to — never a foreign origin.
///
/// Everything else is preserved verbatim: other directives, their
/// spacing, a `form-action` that names other sources (an operator's
/// deliberate choice — the CSP cookbook documents how to widen it by
/// hand), and a policy with no `form-action` at all. Returns `None`
/// in every untouched case, and when `family` is empty.
pub(crate) fn expand_form_action(policy: &str, family: &[String]) -> Option<String> {
    if family.is_empty() {
        return None;
    }
    for (index, directive) in policy.split(';').enumerate() {
        let mut parts = directive.split_ascii_whitespace();
        if !parts
            .next()
            .is_some_and(|name| name.eq_ignore_ascii_case("form-action"))
        {
            continue;
        }
        let sources: Vec<&str> = parts.collect();
        // Only the `'self'` shape is widened; any other source list
        // is an operator's own policy.
        if !sources.contains(&"'self'") {
            return None;
        }
        let additions: Vec<&str> = family
            .iter()
            .map(String::as_str)
            .filter(|source| !sources.contains(source))
            .collect();
        if additions.is_empty() {
            return None;
        }
        let mut widened = String::from("form-action");
        for source in sources.iter().chain(additions.iter()) {
            widened.push(' ');
            widened.push_str(source);
        }
        let mut rebuilt = String::with_capacity(policy.len());
        for (position, segment) in policy.split(';').enumerate() {
            if position > 0 {
                rebuilt.push(';');
            }
            if position == index {
                rebuilt.push_str(&widened);
            } else {
                rebuilt.push_str(segment);
            }
        }
        return Some(rebuilt);
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    const POLICY: &str = "default-src 'none'; style-src 'self'; img-src 'self' data:; \
                          form-action 'self'; frame-ancestors 'none'; base-uri 'none'";

    fn family() -> Vec<String> {
        vec![
            String::from("http://app.localhost:8080"),
            String::from("http://*.app.localhost:8080"),
        ]
    }

    #[test]
    fn the_family_rides_along_form_action_self() {
        let expanded = expand_form_action(POLICY, &family()).expect("widened");
        assert!(
            expanded.contains(
                "form-action 'self' http://app.localhost:8080 \
                               http://*.app.localhost:8080;"
            ),
            "{expanded}"
        );
        // The other directives survive verbatim.
        assert!(expanded.starts_with("default-src 'none'; style-src 'self';"));
        assert!(expanded.contains("frame-ancestors 'none'; base-uri 'none'"));
    }

    #[test]
    fn already_listed_sources_are_not_duplicated() {
        let mut listed = family();
        listed.push(String::from("http://elsewhere.example"));
        let expanded = expand_form_action(
            "form-action 'self' http://app.localhost:8080; default-src 'none'",
            &listed,
        )
        .expect("widened");
        assert_eq!(
            expanded,
            "form-action 'self' http://app.localhost:8080 http://*.app.localhost:8080 \
             http://elsewhere.example; default-src 'none'"
        );
    }

    #[test]
    fn untouched_policies_stay_untouched() {
        // No family, no widening.
        assert_eq!(expand_form_action(POLICY, &[]), None);
        // No form-action at all.
        assert_eq!(
            expand_form_action("default-src 'none'; frame-ancestors 'none'", &family()),
            None
        );
        // A form-action without 'self' is the operator's own choice.
        assert_eq!(
            expand_form_action(
                "form-action https://only.example; default-src 'none'",
                &family()
            ),
            None
        );
        // A form-action with no sources is not a policy to build on.
        assert_eq!(
            expand_form_action("form-action; default-src 'none'", &family()),
            None
        );
        // Directive names match case-insensitively (CSP grammar).
        assert!(expand_form_action("FORM-ACTION 'self'; default-src 'none'", &family()).is_some());
    }
}
